/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author filli
 */
public class Painel extends javax.swing.JFrame {

   static private int numero1 = 0;
   static private int numero2 = 0;
   static private int result = 0;
   
   static int soma(){
       int soma = 0;
       soma = numero1 + numero2;
       return soma;
   }
   

   
    static int multiplicar(){
        int multi = 0;
        multi = numero1 * numero2;
        
        return multi;
    }
    
      static int Subtracao(){
        int sub = 0;
        sub = numero1 - numero2;
        
        return sub;
    }
      
      static int Divisao(){
        int div = 0;
        div = numero1 / numero2;
        
        return div;
    }
    
    
    
    public Painel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BSOMAR = new javax.swing.JButton();
        BDIVIDIR = new javax.swing.JButton();
        BSUBTRAIR = new javax.swing.JButton();
        BMULTIPLICAR = new javax.swing.JButton();
        CAMPONUM = new javax.swing.JTextField();
        CAMPONUM2 = new javax.swing.JTextField();
        CAMPORESULTADO = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Calculadora 1.0 - Estrutura de Dados");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 320, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/promove2.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 210, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Promove - Estrutura de Dados - Prof. Augusto Zadra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 370, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Calculadora 1.0 - Fillipe Augusto Rodrigues");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 370, 30));

        BSOMAR.setText("SOMAR");
        BSOMAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSOMARActionPerformed(evt);
            }
        });
        getContentPane().add(BSOMAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 110, 30));

        BDIVIDIR.setText("DIVIDR");
        BDIVIDIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDIVIDIRActionPerformed(evt);
            }
        });
        getContentPane().add(BDIVIDIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 110, 30));

        BSUBTRAIR.setText("SUBTRAIR");
        BSUBTRAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSUBTRAIRActionPerformed(evt);
            }
        });
        getContentPane().add(BSUBTRAIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 30));

        BMULTIPLICAR.setText("MULTIPLICAR");
        BMULTIPLICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMULTIPLICARActionPerformed(evt);
            }
        });
        getContentPane().add(BMULTIPLICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 110, 30));

        CAMPONUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPONUMActionPerformed(evt);
            }
        });
        getContentPane().add(CAMPONUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 230, 40));

        CAMPONUM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPONUM2ActionPerformed(evt);
            }
        });
        getContentPane().add(CAMPONUM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 230, 40));

        CAMPORESULTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMPORESULTADOActionPerformed(evt);
            }
        });
        getContentPane().add(CAMPORESULTADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 400, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Painel.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSOMARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSOMARActionPerformed
        //int resultado = numero1 + numero1;
        //this.CAMPORESULTADO.setText(Integer.valueOf(this.CAMPONUM.getText()) + (this.CAMPONUM2.getText()));
        this.numero1 = Integer.parseInt(this.CAMPONUM.getText());
        this.numero2 = Integer.parseInt(this.CAMPONUM2.getText());
        this.CAMPORESULTADO.setText(String.valueOf(this.soma()));
    }//GEN-LAST:event_BSOMARActionPerformed

    private void BSUBTRAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSUBTRAIRActionPerformed
        this.numero1 = Integer.parseInt(this.CAMPONUM.getText());
        this.numero2 = Integer.parseInt(this.CAMPONUM2.getText());
        this.CAMPORESULTADO.setText(String.valueOf(this.Subtracao()));
    }//GEN-LAST:event_BSUBTRAIRActionPerformed

    private void BMULTIPLICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMULTIPLICARActionPerformed
         this.numero1 = Integer.parseInt(this.CAMPONUM.getText());
        this.numero2 = Integer.parseInt(this.CAMPONUM2.getText());
        this.CAMPORESULTADO.setText(String.valueOf(this.multiplicar()));
    }//GEN-LAST:event_BMULTIPLICARActionPerformed

    private void BDIVIDIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDIVIDIRActionPerformed
        this.numero1 = Integer.parseInt(this.CAMPONUM.getText());
        this.numero2 = Integer.parseInt(this.CAMPONUM2.getText());
        this.CAMPORESULTADO.setText(String.valueOf(this.Divisao()));
    }//GEN-LAST:event_BDIVIDIRActionPerformed

    private void CAMPONUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPONUMActionPerformed
        this.setNumero1(Integer.parseInt(this.CAMPONUM.getText()));
    }//GEN-LAST:event_CAMPONUMActionPerformed

    private void CAMPORESULTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPORESULTADOActionPerformed
        this.CAMPORESULTADO.setText(String.valueOf(this.CAMPONUM.getText()));
        
        
    }//GEN-LAST:event_CAMPORESULTADOActionPerformed

    private void CAMPONUM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMPONUM2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAMPONUM2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDIVIDIR;
    private javax.swing.JButton BMULTIPLICAR;
    private javax.swing.JButton BSOMAR;
    private javax.swing.JButton BSUBTRAIR;
    private javax.swing.JTextField CAMPONUM;
    private javax.swing.JTextField CAMPONUM2;
    private javax.swing.JTextField CAMPORESULTADO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numero1
     */
    public int getNumero1() {
        return numero1;
    }

    /**
     * @param numero1 the numero1 to set
     */
    public void setNumero1(int numero1) {
        this.numero1 = numero1;
    }

    /**
     * @return the numero2
     */
    public int getNumero2() {
        return numero2;
    }

    /**
     * @param numero2 the numero2 to set
     */
    public void setNumero2(int numero2) {
        this.numero2 = numero2;
    }

    /**
     * @return the result
     */
    public int getResult() {
        return result;
    }

    /**
     * @param result the result to set
     */
    public void setResult(int result) {
        this.result = result;
    }

    private String result() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
